version: ~> 1.0

language: php
dist: xenial

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

# Since Xenial services are not started by default, we need to instruct it below to start.
services:
  - xvfb
  - mysql
  - docker

# Test main supported versions of PHP against latest WP.
php:
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest

# Additional tests against stable PHP (min version is 7.0)
# and code coverage report.

before_script:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - nvm install 10
  - npm install
  - travis_retry composer update --ignore-platform-reqs --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

# Specifies that Travis should create builds for master and release branches and also tags.
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^release\//
